Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\AbstractBaseController",
            "name": "AbstractBaseController",
            "summary": "Class\u0020AbstractBaseController.",
            "url": "classes/App-Dvidz-Rest-Controller-AbstractBaseController.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\AbstractBaseController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Controller-AbstractBaseController.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\AbstractBaseController\u003A\u003A\u0024bookmarkService",
            "name": "bookmarkService",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Controller-AbstractBaseController.html#property_bookmarkService"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\AbstractBaseController\u003A\u003A\u0024bus",
            "name": "bus",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Controller-AbstractBaseController.html#property_bus"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\ListBookmarkController",
            "name": "ListBookmarkController",
            "summary": "Class\u0020ListBookmarkController",
            "url": "classes/App-Dvidz-Rest-Controller-ListBookmarkController.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\ListBookmarkController\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Controller-ListBookmarkController.html#method___invoke"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\PostBookmarkController",
            "name": "PostBookmarkController",
            "summary": "Class\u0020PostBookmarkController.",
            "url": "classes/App-Dvidz-Rest-Controller-PostBookmarkController.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\PostBookmarkController\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Controller-PostBookmarkController.html#method___invoke"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\RemoveBookmarkController",
            "name": "RemoveBookmarkController",
            "summary": "Class\u0020RemoveBookmarkController.",
            "url": "classes/App-Dvidz-Rest-Controller-RemoveBookmarkController.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller\\RemoveBookmarkController\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Controller-RemoveBookmarkController.html#method___invoke"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark",
            "name": "AbstractBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getUrl"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetUrl\u0028\u0029",
            "name": "setUrl",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setUrl"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetProviderName\u0028\u0029",
            "name": "getProviderName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getProviderName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetLinkTitle\u0028\u0029",
            "name": "getLinkTitle",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getLinkTitle"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetLinkTitle\u0028\u0029",
            "name": "setLinkTitle",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setLinkTitle"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetLinkAuthor\u0028\u0029",
            "name": "getLinkAuthor",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getLinkAuthor"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetLinkAuthor\u0028\u0029",
            "name": "setLinkAuthor",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setLinkAuthor"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetCreatedAt\u0028\u0029",
            "name": "getCreatedAt",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getCreatedAt"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetCreatedAt\u0028\u0029",
            "name": "setCreatedAt",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setCreatedAt"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetPublicationDate\u0028\u0029",
            "name": "getPublicationDate",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getPublicationDate"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetPublicationDate\u0028\u0029",
            "name": "setPublicationDate",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setPublicationDate"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetTypeLink\u0028\u0029",
            "name": "getTypeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getTypeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetTypeLink\u0028\u0029",
            "name": "setTypeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setTypeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetLinkProvider\u0028\u0029",
            "name": "getLinkProvider",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getLinkProvider"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetLinkProvider\u0028\u0029",
            "name": "setLinkProvider",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setLinkProvider"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetImageSize\u0028\u0029",
            "name": "getImageSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getImageSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetImageSize\u0028\u0029",
            "name": "setImageSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setImageSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AgetVideoSize\u0028\u0029",
            "name": "getVideoSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_getVideoSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003AsetVideoSize\u0028\u0029",
            "name": "setVideoSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#method_setVideoSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_id"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_url"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024providerName",
            "name": "providerName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_providerName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024linkTitle",
            "name": "linkTitle",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_linkTitle"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024linkAuthor",
            "name": "linkAuthor",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_linkAuthor"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024createdAt",
            "name": "createdAt",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_createdAt"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024publicationDate",
            "name": "publicationDate",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_publicationDate"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024typeLink",
            "name": "typeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_typeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024linkProvider",
            "name": "linkProvider",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_linkProvider"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024imageSize",
            "name": "imageSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_imageSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractBookmark\u003A\u003A\u0024videoSize",
            "name": "videoSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractBookmark.html#property_videoSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractMediaSize",
            "name": "AbstractMediaSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractMediaSize.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractMediaSize\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractMediaSize.html#method_getId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractMediaSize\u003A\u003AgetWidth\u0028\u0029",
            "name": "getWidth",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractMediaSize.html#method_getWidth"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractMediaSize\u003A\u003AsetWidth\u0028\u0029",
            "name": "setWidth",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractMediaSize.html#method_setWidth"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractMediaSize\u003A\u003AgetHeight\u0028\u0029",
            "name": "getHeight",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractMediaSize.html#method_getHeight"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractMediaSize\u003A\u003AsetHeight\u0028\u0029",
            "name": "setHeight",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractMediaSize.html#method_setHeight"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractMediaSize\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractMediaSize.html#property_id"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractMediaSize\u003A\u003A\u0024width",
            "name": "width",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractMediaSize.html#property_width"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\AbstractMediaSize\u003A\u003A\u0024height",
            "name": "height",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-AbstractMediaSize.html#property_height"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\Bookmark",
            "name": "Bookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-Bookmark.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface",
            "name": "BookmarkInterface",
            "summary": "Interface\u0020BookmarkInterface.",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getUrl"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AsetUrl\u0028\u0029",
            "name": "setUrl",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_setUrl"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetProviderName\u0028\u0029",
            "name": "getProviderName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getProviderName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetLinkTitle\u0028\u0029",
            "name": "getLinkTitle",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getLinkTitle"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AsetLinkTitle\u0028\u0029",
            "name": "setLinkTitle",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_setLinkTitle"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetLinkAuthor\u0028\u0029",
            "name": "getLinkAuthor",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getLinkAuthor"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AsetLinkAuthor\u0028\u0029",
            "name": "setLinkAuthor",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_setLinkAuthor"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetCreatedAt\u0028\u0029",
            "name": "getCreatedAt",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getCreatedAt"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AsetCreatedAt\u0028\u0029",
            "name": "setCreatedAt",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_setCreatedAt"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetPublicationDate\u0028\u0029",
            "name": "getPublicationDate",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getPublicationDate"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AsetPublicationDate\u0028\u0029",
            "name": "setPublicationDate",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_setPublicationDate"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetTypeLink\u0028\u0029",
            "name": "getTypeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getTypeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetVideoSize\u0028\u0029",
            "name": "getVideoSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getVideoSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\BookmarkInterface\u003A\u003AgetImageSize\u0028\u0029",
            "name": "getImageSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-BookmarkInterface.html#method_getImageSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize",
            "name": "ImageSize",
            "summary": "Class\u0020ImageSize.",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ImageSize\u0020constructors.",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize\u003A\u003AgetTypeLinks\u0028\u0029",
            "name": "getTypeLinks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html#method_getTypeLinks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize\u003A\u003AaddTypeLink\u0028\u0029",
            "name": "addTypeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html#method_addTypeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize\u003A\u003AgetBookmarks\u0028\u0029",
            "name": "getBookmarks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html#method_getBookmarks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize\u003A\u003AaddBookmark\u0028\u0029",
            "name": "addBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html#method_addBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize\u003A\u003AsetDuration\u0028\u0029",
            "name": "setDuration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html#method_setDuration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize\u003A\u003AgetDuration\u0028\u0029",
            "name": "getDuration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html#method_getDuration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize\u003A\u003A\u0024typeLinks",
            "name": "typeLinks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html#property_typeLinks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSize\u003A\u003A\u0024bookmarks",
            "name": "bookmarks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSize.html#property_bookmarks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\ImageSizeInterface",
            "name": "ImageSizeInterface",
            "summary": "Interface\u0020ImageSizeInterface",
            "url": "classes/App-Dvidz-Rest-Entity-ImageSizeInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider",
            "name": "LinkProvider",
            "summary": "Class\u0020LinkProvider.",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "LinkProvider\u0020constructor.",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#method_getId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003AgetProviderName\u0028\u0029",
            "name": "getProviderName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#method_getProviderName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003AsetProviderName\u0028\u0029",
            "name": "setProviderName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#method_setProviderName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003AgetBookmarks\u0028\u0029",
            "name": "getBookmarks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#method_getBookmarks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003AaddBookmark\u0028\u0029",
            "name": "addBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#method_addBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003AgetTypeLinks\u0028\u0029",
            "name": "getTypeLinks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#method_getTypeLinks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003AaddTypeLink\u0028\u0029",
            "name": "addTypeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#method_addTypeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#property_id"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003A\u0024providerName",
            "name": "providerName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#property_providerName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003A\u0024bookmarks",
            "name": "bookmarks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#property_bookmarks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProvider\u003A\u003A\u0024typeLinks",
            "name": "typeLinks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProvider.html#property_typeLinks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProviderInterface",
            "name": "LinkProviderInterface",
            "summary": "Interface\u0020LinkProviderInterface.",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProviderInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProviderInterface\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProviderInterface.html#method_getId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProviderInterface\u003A\u003AgetProviderName\u0028\u0029",
            "name": "getProviderName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProviderInterface.html#method_getProviderName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\LinkProviderInterface\u003A\u003AsetProviderName\u0028\u0029",
            "name": "setProviderName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-LinkProviderInterface.html#method_setProviderName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\MediaSizeInterface",
            "name": "MediaSizeInterface",
            "summary": "Interface\u0020MediaSizeInterface.",
            "url": "classes/App-Dvidz-Rest-Entity-MediaSizeInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\MediaSizeInterface\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-MediaSizeInterface.html#method_getId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\MediaSizeInterface\u003A\u003AgetWidth\u0028\u0029",
            "name": "getWidth",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-MediaSizeInterface.html#method_getWidth"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\MediaSizeInterface\u003A\u003AsetWidth\u0028\u0029",
            "name": "setWidth",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-MediaSizeInterface.html#method_setWidth"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\MediaSizeInterface\u003A\u003AgetHeight\u0028\u0029",
            "name": "getHeight",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-MediaSizeInterface.html#method_getHeight"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\MediaSizeInterface\u003A\u003AsetHeight\u0028\u0029",
            "name": "setHeight",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-MediaSizeInterface.html#method_setHeight"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\MediaSizeInterface\u003A\u003AsetDuration\u0028\u0029",
            "name": "setDuration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-MediaSizeInterface.html#method_setDuration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\MediaSizeInterface\u003A\u003AgetDuration\u0028\u0029",
            "name": "getDuration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-MediaSizeInterface.html#method_getDuration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\MediaSizeInterface\u003A\u003AaddTypeLink\u0028\u0029",
            "name": "addTypeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-MediaSizeInterface.html#method_addTypeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink",
            "name": "TypeLink",
            "summary": "Class\u0020TypeLink",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "TypeLink\u0020Constructor.",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_getId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AgetTypeLinkName\u0028\u0029",
            "name": "getTypeLinkName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_getTypeLinkName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AsetTypeLinkName\u0028\u0029",
            "name": "setTypeLinkName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_setTypeLinkName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AgetBookmarks\u0028\u0029",
            "name": "getBookmarks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_getBookmarks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AaddBookmark\u0028\u0029",
            "name": "addBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_addBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AgetLinkProviders\u0028\u0029",
            "name": "getLinkProviders",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_getLinkProviders"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AaddLinkProvider\u0028\u0029",
            "name": "addLinkProvider",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_addLinkProvider"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AgetImageSizes\u0028\u0029",
            "name": "getImageSizes",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_getImageSizes"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AaddImageSize\u0028\u0029",
            "name": "addImageSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_addImageSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AgetVideoSizes\u0028\u0029",
            "name": "getVideoSizes",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_getVideoSizes"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003AaddVideoSize\u0028\u0029",
            "name": "addVideoSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#method_addVideoSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#property_id"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003A\u0024typeLinkName",
            "name": "typeLinkName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#property_typeLinkName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003A\u0024bookmarks",
            "name": "bookmarks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#property_bookmarks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003A\u0024linkProviders",
            "name": "linkProviders",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#property_linkProviders"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003A\u0024imageSizes",
            "name": "imageSizes",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#property_imageSizes"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLink\u003A\u003A\u0024videoSizes",
            "name": "videoSizes",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLink.html#property_videoSizes"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLinkInterface",
            "name": "TypeLinkInterface",
            "summary": "Interface\u0020TypeLinkInterface.",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLinkInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLinkInterface\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLinkInterface.html#method_getId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLinkInterface\u003A\u003AgetTypeLinkName\u0028\u0029",
            "name": "getTypeLinkName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLinkInterface.html#method_getTypeLinkName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLinkInterface\u003A\u003AsetTypeLinkName\u0028\u0029",
            "name": "setTypeLinkName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLinkInterface.html#method_setTypeLinkName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLinkInterface\u003A\u003AaddVideoSize\u0028\u0029",
            "name": "addVideoSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLinkInterface.html#method_addVideoSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\TypeLinkInterface\u003A\u003AaddImageSize\u0028\u0029",
            "name": "addImageSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-TypeLinkInterface.html#method_addImageSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize",
            "name": "VideoSize",
            "summary": "Class\u0020VideoSize.",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "VideoSize\u0020constructor.",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003AgetDuration\u0028\u0029",
            "name": "getDuration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#method_getDuration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003AsetDuration\u0028\u0029",
            "name": "setDuration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#method_setDuration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003AgetTypeLinks\u0028\u0029",
            "name": "getTypeLinks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#method_getTypeLinks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003AaddTypeLink\u0028\u0029",
            "name": "addTypeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#method_addTypeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003AgetBookmarks\u0028\u0029",
            "name": "getBookmarks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#method_getBookmarks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003AaddBookmark\u0028\u0029",
            "name": "addBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#method_addBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003A\u0024duration",
            "name": "duration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#property_duration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003A\u0024typeLinks",
            "name": "typeLinks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#property_typeLinks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSize\u003A\u003A\u0024bookmarks",
            "name": "bookmarks",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSize.html#property_bookmarks"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSizeInterface",
            "name": "VideoSizeInterface",
            "summary": "Interface\u0020VideoSizeInterface.",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSizeInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSizeInterface\u003A\u003AsetDuration\u0028\u0029",
            "name": "setDuration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSizeInterface.html#method_setDuration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity\\VideoSizeInterface\u003A\u003AgetDuration\u0028\u0029",
            "name": "getDuration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Entity-VideoSizeInterface.html#method_getDuration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener\\BookmarkListener",
            "name": "BookmarkListener",
            "summary": "Class\u0020BookmarkListener.",
            "url": "classes/App-Dvidz-Rest-EventListener-BookmarkListener.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener\\BookmarkListener\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-EventListener-BookmarkListener.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener\\BookmarkListener\u003A\u003AonKernelException\u0028\u0029",
            "name": "onKernelException",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-EventListener-BookmarkListener.html#method_onKernelException"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener\\BookmarkListener\u003A\u003AonKernelRequest\u0028\u0029",
            "name": "onKernelRequest",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-EventListener-BookmarkListener.html#method_onKernelRequest"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener\\BookmarkListener\u003A\u003AgetSubscribedEvents\u0028\u0029",
            "name": "getSubscribedEvents",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-EventListener-BookmarkListener.html#method_getSubscribedEvents"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener\\BookmarkListener\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-EventListener-BookmarkListener.html#property_cache"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener\\BookmarkListener\u003A\u003A\u0024bookmarkService",
            "name": "bookmarkService",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-EventListener-BookmarkListener.html#property_bookmarkService"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener\\BookmarkListener\u003A\u003A\u0024requestEvent",
            "name": "requestEvent",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-EventListener-BookmarkListener.html#property_requestEvent"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener\\BookmarkListener\u003A\u003A\u0024bus",
            "name": "bus",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-EventListener-BookmarkListener.html#property_bus"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Exception\\BookmarkAlreadyRegistredException",
            "name": "BookmarkAlreadyRegistredException",
            "summary": "Class\u0020BookmarkAlreadyRegistredException.",
            "url": "classes/App-Dvidz-Rest-Exception-BookmarkAlreadyRegistredException.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Exception\\BookmarkAlreadyRegistredException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Exception-BookmarkAlreadyRegistredException.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Exception\\BookmarkNotFoundException",
            "name": "BookmarkNotFoundException",
            "summary": "Class\u0020BookmarkNotFoundException.",
            "url": "classes/App-Dvidz-Rest-Exception-BookmarkNotFoundException.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Exception\\MalformedUrlException",
            "name": "MalformedUrlException",
            "summary": "Class\u0020MalformedUrlException.",
            "url": "classes/App-Dvidz-Rest-Exception-MalformedUrlException.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Exception\\MediaTypeException",
            "name": "MediaTypeException",
            "summary": "MediaTypeException",
            "url": "classes/App-Dvidz-Rest-Exception-MediaTypeException.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Exception\\NullTypeLinkException",
            "name": "NullTypeLinkException",
            "summary": "Class\u0020NullTypeLinkException.",
            "url": "classes/App-Dvidz-Rest-Exception-NullTypeLinkException.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Message\\NewBookmark",
            "name": "NewBookmark",
            "summary": "Class\u0020NewBookmark",
            "url": "classes/App-Dvidz-Rest-Message-NewBookmark.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Message\\NewBookmark\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Message-NewBookmark.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Message\\NewBookmark\u003A\u003AgetBookmarkId\u0028\u0029",
            "name": "getBookmarkId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Message-NewBookmark.html#method_getBookmarkId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Message\\NewBookmark\u003A\u003A\u0024bookmarkId",
            "name": "bookmarkId",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Message-NewBookmark.html#property_bookmarkId"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\MessageHandler\\NewBookmarkHandler",
            "name": "NewBookmarkHandler",
            "summary": "Class\u0020NewBookmarkHandler.",
            "url": "classes/App-Dvidz-Rest-MessageHandler-NewBookmarkHandler.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\MessageHandler\\NewBookmarkHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-MessageHandler-NewBookmarkHandler.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\MessageHandler\\NewBookmarkHandler\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-MessageHandler-NewBookmarkHandler.html#method___invoke"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\MessageHandler\\NewBookmarkHandler\u003A\u003A\u0024bookmarkRepository",
            "name": "bookmarkRepository",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-MessageHandler-NewBookmarkHandler.html#property_bookmarkRepository"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto",
            "name": "BookmarkModelDto",
            "summary": "Class\u0020BookmarkModelDto.",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_id"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_url"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_type"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024providerName",
            "name": "providerName",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_providerName"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024linkTitle",
            "name": "linkTitle",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_linkTitle"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024linkAuthor",
            "name": "linkAuthor",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_linkAuthor"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024createAt",
            "name": "createAt",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_createAt"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024publishedDate",
            "name": "publishedDate",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_publishedDate"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024videoHeight",
            "name": "videoHeight",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_videoHeight"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024videoWidth",
            "name": "videoWidth",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_videoWidth"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024videoDuration",
            "name": "videoDuration",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_videoDuration"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024imageHeight",
            "name": "imageHeight",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_imageHeight"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkModelDto\u003A\u003A\u0024imageWidth",
            "name": "imageWidth",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkModelDto.html#property_imageWidth"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkViewModel",
            "name": "BookmarkViewModel",
            "summary": "Class\u0020BookmarkViewModel.",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkViewModel.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkViewModel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkViewModel.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkViewModel\u003A\u003AgetViewModel\u0028\u0029",
            "name": "getViewModel",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkViewModel.html#method_getViewModel"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkViewModel\u003A\u003A\u0024mediaSize",
            "name": "mediaSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkViewModel.html#property_mediaSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkViewModelInterface",
            "name": "BookmarkViewModelInterface",
            "summary": "Interface\u0020BookmarkViewModelInterface.",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkViewModelInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\BookmarkViewModelInterface\u003A\u003AgetViewModel\u0028\u0029",
            "name": "getViewModel",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Model-BookmarkViewModelInterface.html#method_getViewModel"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model\\ViewModelInterface",
            "name": "ViewModelInterface",
            "summary": "Interface\u0020ViewModelInterface.",
            "url": "classes/App-Dvidz-Rest-Model-ViewModelInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\BookmarkRepository",
            "name": "BookmarkRepository",
            "summary": "Class\u0020BookmarkRepository.",
            "url": "classes/App-Dvidz-Rest-Repository-BookmarkRepository.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\BookmarkRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Repository-BookmarkRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\BookmarkRepository\u003A\u003AsaveBookmark\u0028\u0029",
            "name": "saveBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Repository-BookmarkRepository.html#method_saveBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\BookmarkRepository\u003A\u003AremoveBookmark\u0028\u0029",
            "name": "removeBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Repository-BookmarkRepository.html#method_removeBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\BookmarkRepositoryInterface",
            "name": "BookmarkRepositoryInterface",
            "summary": "Class\u0020BookmarkRepositoryInterface.",
            "url": "classes/App-Dvidz-Rest-Repository-BookmarkRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\BookmarkRepositoryInterface\u003A\u003AsaveBookmark\u0028\u0029",
            "name": "saveBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Repository-BookmarkRepositoryInterface.html#method_saveBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\BookmarkRepositoryInterface\u003A\u003AremoveBookmark\u0028\u0029",
            "name": "removeBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Repository-BookmarkRepositoryInterface.html#method_removeBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\ImageSizeRepository",
            "name": "ImageSizeRepository",
            "summary": "Class\u0020ImageSizeRepository.",
            "url": "classes/App-Dvidz-Rest-Repository-ImageSizeRepository.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\ImageSizeRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Repository-ImageSizeRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\LinkProviderRepository",
            "name": "LinkProviderRepository",
            "summary": "Class\u0020LinkProviderRepository.",
            "url": "classes/App-Dvidz-Rest-Repository-LinkProviderRepository.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\LinkProviderRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Repository-LinkProviderRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\TypeLinkRepository",
            "name": "TypeLinkRepository",
            "summary": "Class\u0020TypeLinkRepository.",
            "url": "classes/App-Dvidz-Rest-Repository-TypeLinkRepository.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\TypeLinkRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Repository-TypeLinkRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\VideoSizeRepository",
            "name": "VideoSizeRepository",
            "summary": "Class\u0020VideoSizeRepository.",
            "url": "classes/App-Dvidz-Rest-Repository-VideoSizeRepository.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository\\VideoSizeRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Repository-VideoSizeRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder",
            "name": "BookMarkBuilder",
            "summary": "Class\u0020BookMarkBuilder.",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder\u003A\u003AbuildLinkProvider\u0028\u0029",
            "name": "buildLinkProvider",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html#method_buildLinkProvider"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder\u003A\u003AbuildTypeLink\u0028\u0029",
            "name": "buildTypeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html#method_buildTypeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder\u003A\u003AbuildMediaSize\u0028\u0029",
            "name": "buildMediaSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html#method_buildMediaSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder\u003A\u003AbuildBookmark\u0028\u0029",
            "name": "buildBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html#method_buildBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder\u003A\u003A\u0024linkProviderRepository",
            "name": "linkProviderRepository",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html#property_linkProviderRepository"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder\u003A\u003A\u0024typeLinkRepository",
            "name": "typeLinkRepository",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html#property_typeLinkRepository"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder\u003A\u003A\u0024videoSizeRepository",
            "name": "videoSizeRepository",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html#property_videoSizeRepository"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookMarkBuilder\u003A\u003A\u0024imageSizeRepository",
            "name": "imageSizeRepository",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookMarkBuilder.html#property_imageSizeRepository"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkBuilderInterface",
            "name": "BookmarkBuilderInterface",
            "summary": "Interface\u0020BookmarkBuilderInterface.",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkBuilderInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkBuilderInterface\u003A\u003AbuildLinkProvider\u0028\u0029",
            "name": "buildLinkProvider",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkBuilderInterface.html#method_buildLinkProvider"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkBuilderInterface\u003A\u003AbuildTypeLink\u0028\u0029",
            "name": "buildTypeLink",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkBuilderInterface.html#method_buildTypeLink"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkBuilderInterface\u003A\u003AbuildMediaSize\u0028\u0029",
            "name": "buildMediaSize",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkBuilderInterface.html#method_buildMediaSize"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkBuilderInterface\u003A\u003AbuildBookmark\u0028\u0029",
            "name": "buildBookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkBuilderInterface.html#method_buildBookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkService",
            "name": "BookmarkService",
            "summary": "Class\u0020BookmarkService.",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkService.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkService.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkService\u003A\u003Abookmark\u0028\u0029",
            "name": "bookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkService.html#method_bookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkService\u003A\u003AgetRepository\u0028\u0029",
            "name": "getRepository",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkService.html#method_getRepository"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkService\u003A\u003AbuildBookmarkModelDto\u0028\u0029",
            "name": "buildBookmarkModelDto",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkService.html#method_buildBookmarkModelDto"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkService\u003A\u003A\u0024crawler",
            "name": "crawler",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkService.html#property_crawler"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkService\u003A\u003A\u0024bookmarkBuilder",
            "name": "bookmarkBuilder",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkService.html#property_bookmarkBuilder"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkService\u003A\u003A\u0024bookmarkRepository",
            "name": "bookmarkRepository",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkService.html#property_bookmarkRepository"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkServiceInterface",
            "name": "BookmarkServiceInterface",
            "summary": "Interface\u0020BookmarkServiceInterface.",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkServiceInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkServiceInterface\u003A\u003Abookmark\u0028\u0029",
            "name": "bookmark",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkServiceInterface.html#method_bookmark"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\BookmarkServiceInterface\u003A\u003AgetRepository\u0028\u0029",
            "name": "getRepository",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-BookmarkServiceInterface.html#method_getRepository"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\CrawlerInterface",
            "name": "CrawlerInterface",
            "summary": "Interface\u0020CrawlerInterface.",
            "url": "classes/App-Dvidz-Rest-Service-CrawlerInterface.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\CrawlerInterface\u003A\u003Acrawl\u0028\u0029",
            "name": "crawl",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-CrawlerInterface.html#method_crawl"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\LinkCrawlerService",
            "name": "LinkCrawlerService",
            "summary": "Class\u0020LinkScrapperService.",
            "url": "classes/App-Dvidz-Rest-Service-LinkCrawlerService.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\LinkCrawlerService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-LinkCrawlerService.html#method___construct"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\LinkCrawlerService\u003A\u003Acrawl\u0028\u0029",
            "name": "crawl",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-LinkCrawlerService.html#method_crawl"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\LinkCrawlerService\u003A\u003AextractMetaValue\u0028\u0029",
            "name": "extractMetaValue",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-LinkCrawlerService.html#method_extractMetaValue"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service\\LinkCrawlerService\u003A\u003A\u0024scrapper",
            "name": "scrapper",
            "summary": "",
            "url": "classes/App-Dvidz-Rest-Service-LinkCrawlerService.html#property_scrapper"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureContainer\u0028\u0029",
            "name": "configureContainer",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureContainer"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureRoutes\u0028\u0029",
            "name": "configureRoutes",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureRoutes"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-dvidz-rest-controller.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest",
            "name": "Rest",
            "summary": "",
            "url": "namespaces/app-dvidz-rest.html"
        },                {
            "fqsen": "\\App\\Dvidz",
            "name": "Dvidz",
            "summary": "",
            "url": "namespaces/app-dvidz.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-dvidz-rest-entity.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\EventListener",
            "name": "EventListener",
            "summary": "",
            "url": "namespaces/app-dvidz-rest-eventlistener.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/app-dvidz-rest-exception.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Message",
            "name": "Message",
            "summary": "",
            "url": "namespaces/app-dvidz-rest-message.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\MessageHandler",
            "name": "MessageHandler",
            "summary": "",
            "url": "namespaces/app-dvidz-rest-messagehandler.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Model",
            "name": "Model",
            "summary": "",
            "url": "namespaces/app-dvidz-rest-model.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-dvidz-rest-repository.html"
        },                {
            "fqsen": "\\App\\Dvidz\\Rest\\Service",
            "name": "Service",
            "summary": "",
            "url": "namespaces/app-dvidz-rest-service.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        }            ]
);
